import { bigserial, date, index, jsonb, pgTable, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { user } from "./auth";

/**
 * The ledger. Append-only. `id` is generated by the client so sync is a set union;
 * `server_seq` is assigned here so clients can pull "everything after N".
 */
export const ledgerEvents = pgTable(
  "ledger_events",
  {
    id: uuid("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true, mode: "string" }).notNull(),
    tz: text("tz").notNull(),
    deviceId: text("device_id").notNull(),
    payload: jsonb("payload").notNull(),
    serverSeq: bigserial("server_seq", { mode: "number" }).notNull().unique(),
    receivedAt: timestamp("received_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  },
  (t) => [index("ledger_events_user_seq_idx").on(t.userId, t.serverSeq)],
);

/** One settings document per user, last-write-wins by updated_at. */
export const userSettings = pgTable("user_settings", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  doc: jsonb("doc").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull(),
});

export const pushSubscriptions = pgTable("push_subscriptions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  endpoint: text("endpoint").notNull().unique(),
  p256dh: text("p256dh").notNull(),
  auth: text("auth").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

/** Idempotence for the reminder dispatcher: one row per user, prayer day and reminder kind. */
export const reminderDispatches = pgTable(
  "reminder_dispatches",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    prayerDay: date("prayer_day").notNull(),
    kind: text("kind").notNull(),
    sentAt: timestamp("sent_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.prayerDay, t.kind] })],
);
